
# Configuration file for the servers in the Sandbox
# Settings are specifically for test situations and not for deployment
# situations!
#
[Account]
  user = 'test_user'
  pwd = 'T3st-Us3r'

[Binaries]
  mongod = '/home/marcel/Languages/Perl6/Projects/Library/Travis-ci/MongoDB/mongod'

[mongod]
  nojournal = true
  fork = true
  smallfiles = true
  oplogSize = 128
  #ipv6 = true
  #quiet = true
  #verbose = '=command=v =nework=v'
  verbose = 'vv'
  logappend = true


# Configuration for Server 1
#
[mongod.s1]
  logpath = '/home/marcel/Languages/Perl6/Projects/Library/Sandbox/Server1/m.log'
  pidfilepath = '/home/marcel/Languages/Perl6/Projects/Library/Sandbox/Server1/m.pid'
  dbpath = '/home/marcel/Languages/Perl6/Projects/Library/Sandbox/Server1/m.data'
  port = 65100

