branches:
  only:
    - master

language: perl6

perl6:
  - latest

before_install:
  # See also https://www.mongodb.org/dl/linux/
  - sh $TRAVIS_BUILD_DIR/t/Travis-ci/install-mongodb.sh 3.2.9

install:
  - rakudobrew build zef
  - zef --/test --depsonly install .
