branches:
  only:
    - master

language: perl6

perl6:
  - latest

install:
  - sh $HOME/Travis-ci/install-mongodb.sh 3.2.9
  - sh $HOME/Travis-ci/install-zef.sh

  - zef --/test install Data::Dump::Tree
  - zef --/test install Config::TOML
  - zef --/test install MongoDB
  - zef --depsonly install .

cache:
  directories:
    - $HOME/Travis-ci
    - $HOME/.rakudobrew
