[ option.xml-prelude ]
  show          = true

[ option.doctype ]
  show          = true

[ option.doctype.entities ]
  library       = 'Library'
  nbsp          = ' '

[output]
  fileext       = 'xml'

[ output.program ]
  pdf           = 'xsltproc --encoding utf-8 --xinclude %op/library-style.xsl - | xep -fo - -pdf %of.pdf'
  xsl           = 'xmllint --format - > %of.xsl'
  xml           = 'xmllint --format - > %of.%oe'
  chk           = 'xmllint --format - | tee library.xml | rnv /usr/share/xml/docbook5/schema/rng/5.0/docbook.rnc'

[ module ]
  lorem         = 'SxmlLib::LoremIpsum'
  d5b           = 'SxmlLib::Docbook5::Basic'
  d5f           = 'SxmlLib::Docbook5::FixedLayout'
  file          = 'SxmlLib::File'
