#------------------------------------------------------------------------------
[ C ]
  tracing       = true

[ C.db5 ]
  xml-show      = true
  doctype-show  = true

[ C.xsl ]
  xml-show      = true

#------------------------------------------------------------------------------
[ E.db5 ]
  library       = 'Library'
  nbsp          = ' '

#------------------------------------------------------------------------------
[ S ]
  fileroot      = 'doc/Manual'

[ S.xml ]
  filepath      = 'Xml'

[ S.xsl ]
  filepath      = 'Xsl'

[ S.chk ]
  filepath      = 'Xml'

#------------------------------------------------------------------------------
[ R.db5 ]
  pdf           = 'xsltproc --encoding utf-8 --xinclude %op/Xsl/library-style.xsl - | xep -fo - -pdf "%op/%of.%oe"'
  xsl           = 'xmllint --format - > "%op/%of.%oe"'
  xml           = 'xmllint --format - > "%op/%of.%oe"'
  chk           = 'xmllint --format - | tee "%op/%of.%oe" | rnv /usr/share/xml/docbook5/schema/rng/5.0/docbook.rnc'

#------------------------------------------------------------------------------
[ ML.db5 ]
  lorem         = 'SxmlLib::LoremIpsum'
  d5b           = 'SxmlLib::Docbook5::Basic'
  d5f           = 'SxmlLib::Docbook5::FixedLayout'
  file          = 'SxmlLib::File'
